---
include:
  - board: ergohaven
    shield: k03_left
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y
    
  - board: ergohaven
    shield: trackball
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y

  - board: ergohaven
    shield: settings_reset
